name: Ubuntu - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print current directory
        run: echo "Current directory: $(pwd)"

      - name: Run Downloads.sh
        run: bash ./Downloads.sh
      
      - name: List files in current directory
        run: ls -l
